# Generated by Django 5.0.1 on 2024-01-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionHub', '0004_rename_author_comment_author_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopicTag',
            new_name='Topic',
        ),
    ]
