# Generated by Django 5.0.1 on 2024-01-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionHub', '0006_rename_author_id_comment_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
