# Generated by Django 5.0.1 on 2024-01-22 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionHub', '0007_remove_comment_author_remove_post_author_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='QuestionHub.topic'),
        ),
    ]
