# Generated by Django 5.0.1 on 2024-02-07 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionHub', '0008_response_remove_downvote_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='response',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='QuestionHub.post'),
        ),
    ]
