# Generated by Django 5.0.1 on 2024-02-07 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionHub', '0009_topic_alter_response_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_name',
            new_name='name',
        ),
    ]
