# Generated by Django 5.0.1 on 2024-02-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionHub', '0012_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
