# Generated by Django 4.2.11 on 2024-03-20 03:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuestionHub', '0016_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, related_name='pending_friend_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
